# local setup with git repo
#spring.cloud.config.server.git.uri = file:///C:/Users/CatalinChelariu/Documents/projects/learning/Microservices-With-Spring-Student-Files-master/ConfigData/
#server.port: 8001

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
#        # "native" is used when the native profile is active, for local tests with a classpath repo:
#        native:
#          searchLocations: classpath:offline-repository/
server:
  port: 8001